[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/articles"
  to = "/articles.html"
  status = 200

[[redirects]]
  from = "/article-1"
  to = "/article-1.html"
  status = 200

[[redirects]]
  from = "/article-mavundla"
  to = "/article-mavundla.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
